name: "Wait for Netlify Deploy"
description: "Wait for Netlify Deploy to complete"
branding:
  icon: "clock"
  color: "blue"
inputs:
  site_id:
    description: "The Netlify site API id"
    required: true
  max_timeout:
    description: "The max time to run the action"
    required: false
outputs:
  url:
    description: "The fully qualified deploy URL"
runs:
  using: "node12"
  main: "index.js"
